export const tech_stack: Record<string, string[]> = {
  Languages: [
    "Python",
    "C++",
    "TypeScript",
    "JavaScript",
    "Rust",
    "Go",
    "Lua",
    "Bash",
    "HTML",
    "CSS",
  ],
  Frameworks: [
    "Next.js",
    "React",
    "React Native",
    "NestJS",
    "Django",
    "FastAPI",
    "Flask",
    "Node.js",
    "Qt",
    "Tailwind CSS",
    "Bootstrap",
    "Vite",
    "Storybook",
  ],
  Infrastructure: [
    "Docker",
    "Kubernetes",
    "Terraform",
    "ArgoCD",
    "AWS",
    "GitLab CI",
    "GitHub Actions",
    "Jenkins",
    "CircleCI",
    "Prometheus",
    "Grafana",
    "NGINX",
    "Apache",
    "Heroku",
    "Linux",
  ],
  "Data & Messaging": [
    "PostgreSQL",
    "SQLite",
    "Redis",
    "MongoDB",
    "Elasticsearch",
    "NATS",
    "Prisma",
    "gRPC",
    "REST",
    "GraphQL",
  ],
  Blockchain: ["Solana", "TON"],
  Testing: ["Pytest", "Selenium", "Vitest", "Playwright"],
};
